FROM node:20-slim

# 安装 openssl 和 libssl-dev，只需构建一次
RUN apt-get update -y && \
    apt-get install -y openssl libssl-dev

# 安装 pnpm
RUN corepack enable && \
    rm -f /usr/local/bin/pnpm && \
    rm -f /usr/local/bin/pnpx && \
    npm install -g pnpm

WORKDIR /app 